sonar.projectKey=CalculatorBackend
sonar.working.directory=D:\\QA1\\Backend\\.sonarqube\\out\\.sonar
sonar.projectBaseDir=D:\\QA1\\Backend
sonar.pullrequest.cache.basepath=D:\\QA1\\Backend

3DBF0099-00EA-4B75-9610-7D409FABDBB7.sonar.projectKey=CalculatorBackend:3DBF0099-00EA-4B75-9610-7D409FABDBB7
3DBF0099-00EA-4B75-9610-7D409FABDBB7.sonar.projectName=backend
3DBF0099-00EA-4B75-9610-7D409FABDBB7.sonar.projectBaseDir=D:\\QA1\\Backend
3DBF0099-00EA-4B75-9610-7D409FABDBB7.sonar.sourceEncoding=utf-8
3DBF0099-00EA-4B75-9610-7D409FABDBB7.sonar.tests=
3DBF0099-00EA-4B75-9610-7D409FABDBB7.sonar.sources=\
"D:\\QA1\\Backend\\CalculatorBackend.Tests\\obj\\Debug\\net9.0\\.NETCoreApp,Version=v9.0.AssemblyAttributes.cs",\
"D:\\QA1\\Backend\\CalculatorBackend.Tests\\obj\\Debug\\net9.0\\CalculatorBackend.Tests.AssemblyInfo.cs",\
"D:\\QA1\\Backend\\CalculatorBackend.Tests\\obj\\Debug\\net9.0\\CalculatorBackend.Tests.GlobalUsings.g.cs",\
"D:\\QA1\\Backend\\controller\\CalculatorController.cs",\
"D:\\QA1\\Backend\\controller\\CalculatorHistoryController.cs",\
"D:\\QA1\\Backend\\Filters\\APIKeyAuthAttributes.cs",\
"D:\\QA1\\Backend\\Program.cs",\
"D:\\QA1\\Backend\\obj\\Debug\\net9.0\\backend.GlobalUsings.g.cs",\
"D:\\QA1\\Backend\\obj\\Debug\\net9.0\\backend.MvcApplicationPartsAssemblyInfo.cs",\
"D:\\QA1\\Backend\\appsettings.Development.json",\
"D:\\QA1\\Backend\\appsettings.json",\
"D:\\QA1\\Backend\\CalculatorBackend.Tests\\bin\\Debug\\net9.0\\appsettings.Development.json",\
"D:\\QA1\\Backend\\CalculatorBackend.Tests\\bin\\Debug\\net9.0\\appsettings.json",\
"D:\\QA1\\Backend\\CalculatorBackend.Tests\\bin\\Debug\\net9.0\\Backend.deps.json",\
"D:\\QA1\\Backend\\CalculatorBackend.Tests\\bin\\Debug\\net9.0\\Backend.runtimeconfig.json",\
"D:\\QA1\\Backend\\CalculatorBackend.Tests\\bin\\Debug\\net9.0\\Backend.staticwebassets.endpoints.json",\
"D:\\QA1\\Backend\\CalculatorBackend.Tests\\bin\\Debug\\net9.0\\CalculatorBackend.Tests.deps.json",\
"D:\\QA1\\Backend\\CalculatorBackend.Tests\\bin\\Debug\\net9.0\\CalculatorBackend.Tests.runtimeconfig.json",\
"D:\\QA1\\Backend\\CalculatorBackend.Tests\\bin\\Debug\\net9.0\\CalculatorBackend.Tests\\obj\\CalculatorBackend.Tests.csproj.nuget.dgspec.json",\
"D:\\QA1\\Backend\\CalculatorBackend.Tests\\bin\\Debug\\net9.0\\CalculatorBackend.Tests\\obj\\project.assets.json",\
"D:\\QA1\\Backend\\CalculatorBackend.Tests\\obj\\CalculatorBackend.Tests.csproj.nuget.dgspec.json",\
"D:\\QA1\\Backend\\CalculatorBackend.Tests\\obj\\Debug\\net9.0\\CalculatorBackend.Tests.sourcelink.json",\
"D:\\QA1\\Backend\\CalculatorBackend.Tests\\obj\\project.assets.json",\
"D:\\QA1\\Backend\\Backend.http",\
"D:\\QA1\\Backend\\CalculatorBackend.Tests\\bin\\Debug\\net9.0\\.msCoverageSourceRootsMapping_CalculatorBackend.Tests",\
"D:\\QA1\\Backend\\CalculatorBackend.Tests\\bin\\Debug\\net9.0\\Backend.pdb",\
"D:\\QA1\\Backend\\CalculatorBackend.Tests\\bin\\Debug\\net9.0\\CalculatorBackend.Tests.pdb",\
"D:\\QA1\\Backend\\CalculatorBackend.Tests\\bin\\Debug\\net9.0\\CoverletSourceRootsMapping_CalculatorBackend.Tests",\
"D:\\QA1\\Backend\\CalculatorBackend.Tests\\bin\\Debug\\net9.0\\NUnit3.TestAdapter.pdb",\
"D:\\QA1\\Backend\\CalculatorBackend.Tests\\obj\\CalculatorBackend.Tests.csproj.nuget.g.props",\
"D:\\QA1\\Backend\\CalculatorBackend.Tests\\obj\\CalculatorBackend.Tests.csproj.nuget.g.targets",\
"D:\\QA1\\Backend\\CalculatorBackend.Tests\\obj\\Debug\\net9.0\\Calculat.6BB0F523.Up2Date",\
"D:\\QA1\\Backend\\CalculatorBackend.Tests\\obj\\Debug\\net9.0\\CalculatorBackend.Tests.AssemblyInfoInputs.cache",\
"D:\\QA1\\Backend\\CalculatorBackend.Tests\\obj\\Debug\\net9.0\\CalculatorBackend.Tests.assets.cache",\
"D:\\QA1\\Backend\\CalculatorBackend.Tests\\obj\\Debug\\net9.0\\CalculatorBackend.Tests.csproj.AssemblyReference.cache",\
"D:\\QA1\\Backend\\CalculatorBackend.Tests\\obj\\Debug\\net9.0\\CalculatorBackend.Tests.csproj.CoreCompileInputs.cache",\
"D:\\QA1\\Backend\\CalculatorBackend.Tests\\obj\\Debug\\net9.0\\CalculatorBackend.Tests.csproj.FileListAbsolute.txt",\
"D:\\QA1\\Backend\\CalculatorBackend.Tests\\obj\\Debug\\net9.0\\CalculatorBackend.Tests.genautoregisteredextensionsinputcache.cache",\
"D:\\QA1\\Backend\\CalculatorBackend.Tests\\obj\\Debug\\net9.0\\CalculatorBackend.Tests.GeneratedMSBuildEditorConfig.editorconfig",\
"D:\\QA1\\Backend\\CalculatorBackend.Tests\\obj\\Debug\\net9.0\\CalculatorBackend.Tests.genruntimeconfig.cache",\
"D:\\QA1\\Backend\\CalculatorBackend.Tests\\obj\\Debug\\net9.0\\CalculatorBackend.Tests.gentestingplatformentrypointinputcache.cache",\
"D:\\QA1\\Backend\\CalculatorBackend.Tests\\obj\\Debug\\net9.0\\CalculatorBackend.Tests.pdb",\
"D:\\QA1\\Backend\\CalculatorBackend.Tests\\obj\\project.nuget.cache",\
"D:\\QA1\\Backend\\calculator_data.csv",\
"D:\\QA1\\Backend\\Properties\\launchSettings.json",\
"D:\\QA1\\Backend\\obj\\backend.csproj.nuget.dgspec.json",\
"D:\\QA1\\Backend\\obj\\project.assets.json",\
"D:\\QA1\\Backend\\bin\\Debug\\net9.0\\appsettings.Development.json",\
"D:\\QA1\\Backend\\bin\\Debug\\net9.0\\appsettings.json",\
"D:\\QA1\\Backend\\bin\\Debug\\net9.0\\backend.deps.json",\
"D:\\QA1\\Backend\\bin\\Debug\\net9.0\\backend.runtimeconfig.json",\
"D:\\QA1\\Backend\\bin\\Debug\\net9.0\\Backend.staticwebassets.endpoints.json",\
"D:\\QA1\\Backend\\obj\\Debug\\net9.0\\Backend.sourcelink.json",\
"D:\\QA1\\Backend\\obj\\Debug\\net9.0\\rjsmcshtml.dswa.cache.json",\
"D:\\QA1\\Backend\\obj\\Debug\\net9.0\\rjsmrazor.dswa.cache.json",\
"D:\\QA1\\Backend\\obj\\Debug\\net9.0\\rpswa.dswa.cache.json",\
"D:\\QA1\\Backend\\obj\\Debug\\net9.0\\staticwebassets.build.endpoints.json",\
"D:\\QA1\\Backend\\obj\\Debug\\net9.0\\staticwebassets.build.json",\
"D:\\QA1\\Backend\\bin\\Debug\\net9.0\\CalculatorBackend.Tests\\obj\\CalculatorBackend.Tests.csproj.nuget.dgspec.json",\
"D:\\QA1\\Backend\\bin\\Debug\\net9.0\\CalculatorBackend.Tests\\obj\\project.assets.json",\
"D:\\QA1\\Backend\\bin\\Debug\\net9.0\\CalculatorBackend.Tests\\bin\\Debug\\net9.0\\appsettings.Development.json",\
"D:\\QA1\\Backend\\bin\\Debug\\net9.0\\CalculatorBackend.Tests\\bin\\Debug\\net9.0\\appsettings.json",\
"D:\\QA1\\Backend\\bin\\Debug\\net9.0\\CalculatorBackend.Tests\\bin\\Debug\\net9.0\\Backend.deps.json",\
"D:\\QA1\\Backend\\bin\\Debug\\net9.0\\CalculatorBackend.Tests\\bin\\Debug\\net9.0\\Backend.runtimeconfig.json",\
"D:\\QA1\\Backend\\bin\\Debug\\net9.0\\CalculatorBackend.Tests\\bin\\Debug\\net9.0\\Backend.staticwebassets.endpoints.json",\
"D:\\QA1\\Backend\\bin\\Debug\\net9.0\\CalculatorBackend.Tests\\bin\\Debug\\net9.0\\CalculatorBackend.Tests.deps.json",\
"D:\\QA1\\Backend\\bin\\Debug\\net9.0\\CalculatorBackend.Tests\\bin\\Debug\\net9.0\\CalculatorBackend.Tests.runtimeconfig.json",\
"D:\\QA1\\Backend\\bin\\Debug\\net9.0\\CalculatorBackend.Tests\\obj\\Debug\\net9.0\\CalculatorBackend.Tests.sourcelink.json",\
"D:\\QA1\\Backend\\bin\\Debug\\net9.0\\CalculatorBackend.Tests\\bin\\Debug\\net9.0\\CalculatorBackend.Tests\\obj\\CalculatorBackend.Tests.csproj.nuget.dgspec.json",\
"D:\\QA1\\Backend\\bin\\Debug\\net9.0\\CalculatorBackend.Tests\\bin\\Debug\\net9.0\\CalculatorBackend.Tests\\obj\\project.assets.json"

3DBF0099-00EA-4B75-9610-7D409FABDBB7.sonar.cs.analyzer.projectOutPaths=\
"D:\\QA1\\Backend\\.sonarqube\\out\\1"
3DBF0099-00EA-4B75-9610-7D409FABDBB7.sonar.cs.roslyn.reportFilePaths=\
"D:\\QA1\\Backend\\.sonarqube\\out\\1\\Issues.json"
3DBF0099-00EA-4B75-9610-7D409FABDBB7.sonar.cs.scanner.telemetry=\
"D:\\QA1\\Backend\\.sonarqube\\out\\1\\Telemetry.json"

3DBF0099-00EA-4B75-9610-7D409FABDBB7.sonar.working.directory=D:\\QA1\\Backend\\.sonarqube\\out\\.sonar\\mod0
sonar.host.url=http://localhost:9000
sonar.visualstudio.enable=false

sonar.modules=3DBF0099-00EA-4B75-9610-7D409FABDBB7

