name: CI-CD Pipeline

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 9.0.x

    - name: Restore dependencies
      run: dotnet restore

    - name: Build
      run: dotnet build --no-restore --configuration Release

    #  Start backend API in background
    - name: Run backend API
      run: |
        nohup dotnet run --project Backend/Backend.csproj --urls "http://localhost:5095" &
        sleep 10  # wait for API to boot up

    - name: Run tests
      run: dotnet test --no-build --configuration Release --logger "trx;LogFileName=test_results.trx"
